### ISSUE TITLE
Setup Documentation Site with Docusaurus

### ISSUE THREAD

**Issue by wopox1337** [rehlds/.github#19]
## Overview

We are creating a comprehensive documentation and community site for all core projects under the ReHLDS organization. The site will be hosted at **ReHLDS/rehlds.github.io** and will be built using [Docusaurus](https://docusaurus.io/). This site will feature detailed documentation for active projects, descriptions of deprecated ones, and best practices and recommendations for users and contributors.

The site will include:
- A **landing page** with clear information about core ReHLDS projects.
- A **blog section** for articles related to problem-solving, community practices, and general information relevant to a healthy community.
- A **GitHub Board** dedicated to tracking and managing tasks related to the site's development.

## Objectives

- Set up a Docusaurus project to host documentation and community information.
- Provide a well-designed **landing page** that informs users about ReHLDS projects.
- Create a **blog** section for community posts, updates, and problem-solving guides.
- Structure the site to include:
  - Documentation for all core projects (ReHLDS, ReGameDLL, ReAPI, etc.).
  - Pages dedicated to deprecated projects with explanations and recommendations.
  - Best practices and guidelines for community contributions and development.
- Create a **GitHub Project Board** to organize and manage tasks for developing the site.

## Tasks

1. **Initialize Docusaurus Project**:
   - Create a new Docusaurus project in the `rehlds.github.io` repository.
   - Set up a clear folder structure for core projects and community content.

2. **Landing Page**:
   - Design a visually engaging **landing page** that gives an overview of ReHLDS projects.
   - Highlight key links to important sections such as Documentation, Blog, and Community Guidelines.

3. **Documentation for Core Projects**:
   - Create detailed documentation for all **core projects** (ReHLDS, ReGameDLL, ReAPI, etc.).
   - Add sections for **deprecated projects**, providing information on their status and migration recommendations.
   - Ensure that each project's page includes setup guides, API references, and troubleshooting.

4. **Blog Setup**:
   - Set up a **blog section** in Docusaurus where community members and maintainers can publish posts.
   - Categories for the blog could include:
     - **Problem-Solving**: Guides to help users fix common issues.
     - **Best Practices**: Advice on improving development processes and community contributions.
     - **Project Updates**: Announcements for new releases and features.
   - Provide a template for writing new blog posts to maintain consistency.

5. **Design and Customization**:
   - Customize the site's visual style to match the branding of ReHLDS (colors, logos, typography).
   - Ensure that the site is fully responsive and mobile-friendly.
   - Add a search function to help users easily find information.

6. **GitHub Board Creation**:
   - Create a **GitHub Project Board** specifically for the documentation site.
   - Organize tasks into columns such as **To Do**, **In Progress**, and **Done**.
   - Ensure that tasks are properly prioritized and regularly updated as development progresses.
   - Assign tasks to relevant contributors and track progress through the board.

7. **Deployment**:
   - Set up GitHub Actions for continuous deployment to **GitHub Pages**.
   - Automatically deploy the site whenever changes are pushed to the repository.

## Acceptance Criteria

- [x] The site is live and accessible at **rehlds.github.io**.
- [x] The blog section is functional and ready for community articles.
- [x] The GitHub Board is created and actively used to manage documentation-related tasks.
- [x] The site is fully responsive and mobile-friendly.
- [x] The documentation is easy to navigate and user-friendly.
- [x] The landing page is informative and visually appealing.
- [x] All core projects have their own documentation pages.
- [ ] Deprecated projects are clearly marked with appropriate recommendations.

## Additional Notes

- Docusaurus supports multi-language documentation, which could be useful in the future.
- Ensure the documentation is easily updatable by the community.

## References

- [Docusaurus Documentation](https://docusaurus.io/docs)
- [GitHub Pages Deployment](https://docs.github.com/en/pages)
- [GitHub Projects](https://docs.github.com/en/issues/trying-out-the-new-projects-experience)

**Comment by wopox1337** [comment]
and add something like this 
```mermaid
graph TD
  A[rehlds] --> B[regamedll_cs]
  A --> C[reapi]
  A --> D[metamod-r]
  B --> E[ReSemiclip]
  B --> F[ReLocalizeBugFix]
  C --> G[WHBlocker]
  C --> H[ReChecker]
  C --> I[SafeNameAndChat]
  D --> J[ReUnion]
  D --> K[HitBox Tracker]
  D --> L[ReFreeLook]
  G --> M[ReVoice]
  H --> N[RoundEndBlock]
  H --> O[LocalizeBugFix]
  
  subgraph Core Components
    A
    B
    C
    D
  end

  subgraph Supporting Modules
    E
    F
    G
    H
    I
    J
    K
    L
    M
    N
    O
  end
  
```
