### ISSUE TITLE
Automatic sync with Gitlab's read-only mirror

### ISSUE THREAD

**Issue by stamepicmorg** [rehlds/.github#23]
Setup workflow with sync from GitHub to Gitlab.

# Proposal

We propose adding a workflow file to each corresponding repository in the ReHLDS organization.

This will allow the same changes to be sent to GitLab automatically with each commit.

# Implementation Steps
1) Create a Template: 

```yml
name: Automatic sync with Gitlab's read-only mirror

on: [workflow_dispatch, push]

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key for Runner
        env:
          SSH_KEY: ${{ secrets.GITLAB_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts

      - name: Clone repository from GitHub as mirror and push to Gitlab
        env:
          REPO_ORIGINAL: "url-github"
          REPO_TARGET:   "ssh-gitlab"
        run: |
          git clone --mirror "$REPO_ORIGINAL" repo-mirror
          cd repo-mirror
          git remote set-url origin "$REPO_TARGET"
          git push --mirror --force
```

2) Add secret to repository with `GITLAB_DEPLOY_KEY` name.

3) Enable deploy key in eah repository at gitlab.

- [x] [hitboxtracker](https://github.com/rehlds/hitboxtracker)
- [x] [metamod-r.org](https://github.com/rehlds/metamod-r.org)
- [x] [relocalizebugfix](https://github.com/rehlds/relocalizebugfix)
- [x] [Metamod-r](https://github.com/rehlds/metamod-r)
- [x] [ReHLDS](https://github.com/rehlds/rehlds)
- [x] [rehlds.github.io](https://github.com/rehlds/rehlds.github.io)
- [x] [revoice](https://github.com/rehlds/revoice)
- [x] [ReFreeLook](https://github.com/rehlds/ReFreeLook)
- [x] [reunion](https://github.com/rehlds/reunion)
- [x] [resemiclip](https://github.com/rehlds/resemiclip)
- [x] [reapi](https://github.com/rehlds/reapi)
- [x] [testdemos](https://github.com/rehlds/testdemos)
- [x] [rechecker](https://github.com/rehlds/rechecker)
- [x] [ReGameDLL_CS](https://github.com/rehlds/ReGameDLL_CS)

**Comment by wopox1337** [comment]
I think we'd better do it in the rehlds/.GitHub CI repo

**Comment by stamepicmorg** [comment]
resolved bu https://github.com/rehlds/.github/commit/2847d3be854324633148f9fb2b0131f99b31e421
